services:
  - type: web
    name: juuminhyo-api
    runtime: python
    buildCommand: |
      apt-get install -y fonts-ipafont-gothic
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
